[metadata]
name = reachy2_qpik
version = 0.1.0
author = Pollen Robotics
author_email = ousmane.thionagne@outlook.com
url = https://github.com/pollen-robotics/python-template
description = Reachy2 Quadratic Programming Inverse Kinematics
long_description = file: README.md
long_description_content_type = text/markdown


[options]
packages = find:
zip_safe = True
include_package_data = True
package_dir=
    =src
install_requires =
    numpy >= 1.26.4, < 2.0.0
    scipy >= 1.8.0, < 2.0.0
    pin
    qpsolvers[quadprog]
    matplotlib
    pycapacity

[options.packages.find]
where=src

[options.package_data]
config_files =
  *.json

[options.extras_require]
dev = black==24.10.0
      flake8==7.1.1
      pytest==7.4.3
      coverage==7.3.2
      mypy==1.8.0
      isort==5.13.2
      pdoc==14.7.0
      pydocstyle==6.3.0
      types-protobuf==6.30.2.20250506

[options.entry_points]
console_scripts = 
    example_entry_point = example.celcius:main

[flake8]
exclude = tests,
            .git,
            .venv,
            __pycache__,
            build,
            img,
            docs

max-line-length = 128
extend-ignore = E203
max-complexity = 12

[coverage:run]
branch=True

[coverage:report]
show_missing=True

[mypy]
ignore_missing_imports = True
exclude = tests
plugins = numpy.typing.mypy_plugin
explicit_package_bases = True

[tool:pytest]
testpaths = tests
markers =   
    online : that requires the sdk server